LGHV-team1/final-project

- .gitignore
> fork testing

- .gitmessage
- contents/views.py
리뷰 수정 기능을 put 방식으로 추가했습니다. 또한 gitmessage를 추가했습니다.
> feat: "Review 수정 기능 추가"

- src/App.css
- src/components/Button.js
- src/components/Rank.js
- src/components/Review.js
- src/page/Detail.js
- src/page/Login.js
상세페이지 구현
1. 별점 기능추가
2. 상세 페이지 ui 
3. 위시리스트 버튼 추가
> [Feat]: "상세페이지 구현"

- src/App.js
- src/components/Header.js
- src/components/Star.js
- src/page/Detail.js
- src/page/Search.js
검색 페이지 기능 구현
1. 검색 기능 구현
2. 랭크 버그 수정
생략
> [Front - feat] 

- contents/management/commands/dbinsert.py
- contents/urls.py
- contents/views.py
- recommends/urls.py
- recommends/views.py
- reviews/serializers.py
- reviews/views.py
- contents 세부 카테고리 진입
- 큰 카테고리 인기 top5 제공
- url에 '/'가 섞여서 오는것을 딕셔너리 형태로 변경해서 진입하도록 변경.
- 검색 시 url은 tv,kids,movie로 오게 되어있음
- 뒤에 세부 카테고리가 붙어 올 수 있는 url로 변경
1. 인기top5 url
`http://127.0.0.1:8000/contents/category/tv/`
2. 세부 카테고리 url
`http://127.0.0.1:8000/contents/category/{BigCategory}/{SmallCategory}`
movie_category = {
"fantasy": "SF/환타지",
"thriller": "공포/스릴러",
"documentary": "다큐멘터리",
"shortfilm": "단편",
"drama": "드라마",
"RoCo": "로맨틱코미디",
"melo": "멜로",
"martial": "무협",
"musical": "뮤지컬",
"western": "서부",
"animation": "애니메이션",
"action": "액션/어드벤쳐",
"history": "역사",
"comedy": "코미디",
"etc": "기타",
}
kids_category = {
"etc": "기타",
"animation": "애니메이션",
"entertainment": "오락",
"study": "학습",
}
tv_category = {
"Neighborhood": "우리동네",
"Sports": "스포츠",
"etc": "미분류",
"Life": "라이프",
"Documentary": "다큐", …
> [Back-Feat] : " contents 세부 카테고리 진입"

- contents/urls.py
> [Back-fix] : "vodreveiw url 수정 " 

- .github/workflows/githubaction.yaml
- accounts/adapters.py
- accounts/serializers.py
- config/settings.py
- http 통신시 쿠키 저장되도록 수정
- 셋탑 번호 미기입시 0으로 기입
구현 사항 요약
1. https에서 사용되는 ```
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
```
코드 False로 수정
2. 셋탑 번호 미기입시 0으로 기입
- hotfix로 인한 생략
> [Back-fix] : "http 통신, 회원가입시 셋탑번호 미기입 처리"

- config/views.py
- contents/views.py
접속 시 csrfToken get
1. 프론트에서 접속 시 csrfToken get 할 수 있도록 index에서 제공
생략
> [Back - Feat] : "접속 시 csrfToken get"

- src/api/ApiService.js
- src/components/Dropdown.js
- src/components/MiniSlide.js
- src/components/ShowData.js
- src/page/Detail.js
- src/page/Kids.js
- src/page/Movie.js
- src/page/Search.js
- src/page/Tv.js
tv movie kids 장르 별 페이지 구성
1. 장르 별 페이지 구성
2. 더보기 기능 추가
> [Feat- front]  tv movie kids 장르 별 페이지 구성

- config/views.py
- contents/serializers.py
"serializer에 count 추가"
1. [프론트요구] VOD LIST serializer에 count 추가
생략
> [Back - Refactor] : "serializer에 count 추가"

- src/components/Dropdown.js
- src/components/ShowData.js
- src/components/SortData.js
- src/components/ViewReview.js
- src/page/Kids.js
- src/page/Login.js
- src/page/Movie.js
- src/page/Tv.js
tv movie kids 정렬 버튼 추가
1. tv movie kids 랜덤 인기 이름 정렬 버튼 추가
2. 카테고리 툴킷 상태에 저장
ex) 실행, 테스트 결과 또는 사진 첨부
> [Feat - front] tv movie kids 정렬 버튼 추가

- .github/workflows/frontgitaction.yaml
- "S3 CI/CD를 위한 gitaction 추가"
1. cicd를 위한 gitaction 추가
생략
> [Front-Docs]    : "S3 CI/CD를 위한 gitaction 추가"

- config/settings.py
- contents/urls.py
- contents/views.py
- recommends/views.py
- wishlists/serializers.py
- wishlist serializers vod_id도 제공하게 수정
- jwt 토큰 도입
- cors,csrf 에 cloudfront url 삽입
- 인기 top10으로 변경
- 추천 번호 없다면 400에러
- wishlist serializers vod_id도 제공하게 수정
- jwt 토큰 도입
- cors,csrf 에 cloudfront url 삽입
> [Back-Refactor] : "wishlist serializers 수정, jwt 토큰 사용"

- config/settings.py
- allowed host 에 배포 서버 추가
- allowed host 에 배포 서버 추가
> [Refactor] : "allowed host 추가"

- config/settings.py
- cors url 오류로 인한 hotfix
- cors url 오류로 인한 hotfix
> [Fix]     : "cors url 오류로 인한 수정"

- public/index.html
> [Fix] : "HTML내 meta추가"

- accounts/views.py
- config/settings.py
[Deploy - Fix] : "이메일인증 후 리다이렉트 수정"
> [Deploy - Fix] : "이메일인증 후 리다이렉트 수정"

- package.json
- src/api/ApiService.js
- src/components/Helload.js
- src/components/MyReview.js
- src/components/MyWish.js
- src/page/Detail.js
- src/page/Home.js
- src/page/tmp/Socialgoogle.js
- src/page/tmp/Socialkakao.js
- src/page/tmp/Socialnaver.js
Proxy 설정 추가
1. 리액트 설정에 Proxy 설정 추가
#161
> [Front -Feat] : "Proxy 설정 추가"

- src/api/ApiService.js
- src/index.js
[Front - Fix] : "import 에러 수정"
> [Front - Fix] : "import 에러 수정"

- accounts/serializers.py
> [Back- Fix] : "로그인 안되는 버그 수정"

- reviews/serializers.py
리뷰 포스터를 위한 시리얼라이저 수정
1. 나의리뷰 포스터 이미지를 위한 시리얼라이저 수정
#175 
결과
[
{
"id": 16,
"username": "이멜",
"vodname": "극한직업",
"vodimg": "/jbHNkNydiZstlqhhBSvG19lm4NL.jpg",
"payload": "리뷰",
"rating": 1,
"user": 12,
"contents": 5
}
]
> [Back-Feat] : "리뷰 포스터를 위한 시리얼라이저 수정"

- accounts/apps.py
- config/settings.py
- contents/apps.py
- contents/management/commands/dbinsert.py
- contents/urls.py
- contents/views.py
- recommends/apps.py
- reviews/apps.py
- wishlists/apps.py
- Mongodb CQRS contents 검색 적용
1. runserver 시 mongodb 연동
2. contents 검색 mongodb 에서 조회하도록 변경. 
3. 배우, 영화 검색 url 나눔
#47
> [Feat]    : "Mongodb CQRS 적용 1차"

- src/components/MyReview.js
나의리뷰 포스터 렌더링
1. 나의리뷰 포스터 구현
#175 
이미지는 back에서 받아오기 전이라 엑박입니다...
> [Feat] : "나의리뷰 포스터 렌더링"

- accounts/serializers.py
- reviews/serializers.py
리뷰 포스터를 위한 시리얼라이저 수정
1. 리뷰 포스터를 위한 시리얼라이저 수정
> [Deploy] : "리뷰 포스터를 위한 시리얼라이저 수정"

- contents/urls.py
- contents/views.py
검색 제목 인물 초성 나눠서 구현
1. 검색 제목 인물 초성 나눠서 구현
#182 
path("<str:vodname>", SearchVods.as_view()),
path("search/<str:vodname>", SearchVodsByChoseong.as_view()),
path("search/actor/<str:actor>", Searchactors.as_view()),
> [Back - Feat] : "검색 제목 인물 초성 나눠서 구현"

- contents/urls.py
- contents/views.py
- reviews/serializers.py
검색 제목 인물 초성 나눠서 구현
검색 제목 인물 초성 나눠서 구현
path("<str:vodname>", SearchVods.as_view()),
path("search/<str:vodname>", SearchVodsByChoseong.as_view()),
path("search/actor/<str:actor>", Searchactors.as_view()),
#185
> [Deploy] : "검색 제목 인물 초성 나눠서 구현"

- accounts/views.py
소셜로그인 오류 수정
1. jwt 사용으로 소셜로그인 후 jwt 전달로 수정
> [Back - Fix] : "소셜로그인 오류 수정"

- accounts/apps.py
- config/settings.py
- contents/apps.py
- contents/management/commands/dbinsert.py
- contents/urls.py
- contents/views.py
- recommends/apps.py
- recommends/views.py
- reviews/apps.py
- reviews/views.py
- wishlists/apps.py
- wishlists/urls.py
- wishlists/views.py
- CQRS(읽기/ 쓰기,수정,삭제 분리) 적용
1. 서버 실행시 Mongodb 와 MySQL db 같아짐. 
2. contents CUD/ R 분리
3. Wishlist CQRS 적용
4. recommend CQRS 적용
❗️EC2의 pw, endpoint는 secrets.json 에 저장. 
#182 #165 #47
> [Back- Feat] : "Mongodb 도입을 통한 CQRS 적용"

- task-definition.json
> [Back- Docs]    : "ELB healthcheck를 위한 task-definition 변경"

- package-lock.json
- package.json
- src/components/MiniSlide.js
- src/components/MyReview.js
- src/components/MyWish.js
- src/components/RecMiniSlide.js
- src/components/ShowData.js
- src/components/ShowRec.js
- src/components/SortData.js
- src/components/Top5.js
- src/layout/Footer.js
- src/layout/Header.js
- src/page/Home.js
- src/page/Kids.js
- src/page/Movie.js
- src/page/Mypage.js
- src/page/Search.js
- src/page/Tv.js
- tailwind.config.js
반응형 UI 추가
1. 반응형 UI 추가
2. 더보기 버그 수정 
3. 텍스트 색상 수정
생략
> [Feat - front] : 반응형 UI 추가, 더보기 버그 수정

- src/App.js
- src/page/tmp/Socialgoogle.js
- src/page/tmp/Socialkakao.js
- src/page/tmp/Socialnaver.js
소셜로그인 버그 수정
1. back에서 전달된 access, refesh를 저장 후 삭제
생략
> [Front - Fix] : "소셜로그인 버그 수정"

- src/page/tmp/Socialgoogle.js
- src/page/tmp/Socialkakao.js
- src/page/tmp/Socialnaver.js
> [front- Fix] : "소셜로그인 수정"

- accounts/apps.py
- contents/apps.py
- recommends/apps.py
- reviews/apps.py
- wishlists/apps.py
- mongodb 에서 중복 데이터 처리
1. 같은 Id 가 mongodb에 있다면 가져오지 않음.
#211
> [Back- Feat]    : "mongodb 중복 데이터 처리"

- accounts/apps.py
- contents/apps.py
- recommends/apps.py
- reviews/apps.py
- task-definition.json
- wishlists/apps.py
> [Deploy - server] : "Mongodb 중복 데이터 처리"

- Dockerfile
- accounts/apps.py
- contents/apps.py
- recommends/apps.py
- reviews/apps.py
- sync.py
- wishlists/apps.py
MONGODB 동기화 하는 함수를 따로 제작
1. mongodb 동기화하는 sync.py 함수 제작
2. dockerfile 에서 실행되도록 하여 task 실행시 sync 되는것이 아니라 cmd 로 한번만 실행하도록 변경
#211
> [BACK- Fix]     : "MONGODB 동기화 1회만 수행하도록 수정"

- src/App.js
- src/api/ApiService.js
- src/components/MiniSlide.js
- src/components/ShowData.js
- src/components/ShowRec.js
- src/components/Top5.js
- src/hook/useDebounce.js
- src/layout/Header.js
- src/page/Detail.js
- src/page/First.js
- src/page/Home.js
- src/page/Search.js
- src/page/__Search.js
검색 오류 수정
1. 검색 오류 수정
2. 위시 오류 수정
3. 디테일 페이지 배경 gradient 적용
> [Front - Fix] : 검색, 위시 오류 수정

- recommends/urls.py
- recommends/views.py
- sync.py
> [HOTFix]     : "sync.py 수정"

- sync.py
> [Back-Fix]     : "time sync 에러"

- recommends/views.py
- 시간대별 추천 API 생성
구현 사항 요약
1. 해당 날짜, 어제, 내일 요일 판단해서 추천
2. 공휴일 여부 확인
#14 
API url : /recommend/3
> [Back - Feat]    : "시간대별 추천 API 생성"

- recommends/views.py
- sync.py
[Deploy - Feat]    : "시간대별 추천 API 생성"
> [Deploy - Feat]    : "시간대별 추천 API 생성"

- requirements.txt
- sync.py
requirements.txt 수정
requirements.txt 수정
> [Docs]    : "requirements.txt pytimekr 추가"

- recommends/views.py
- requirements.txt
- sync.py
[Deploy]    : "requirements.txt pytimekr 추가"
> [Deploy]    : "requirements.txt pytimekr 추가"

- contents/management/commands/dbchoseong.py
- contents/management/commands/dbinsert.py
- recommends/views.py
구현 사항 요약
1. db 삽입시 추가되는 데이터만 삽입되도록 함수 수정
2. 토요일이 평일로 인식되는 버그 해결
ex) 실행, 테스트 결과 또는 사진 첨부
> [Fix]     : "토요일이 평일로 인식되는 버그 해결"

- contents/views.py
tv 카테고리창에 bigcategory 제공
1. bigcategory 로 카테고리 제공
2. 미분류에 대해서 기타로 변경해서 제공
ex) 실행, 테스트 결과 또는 사진 첨부
#234
> [Fix]     : "tv pick url에 bigcategory로 serialize"

- contents/views.py
관련 vod 제공 20개중 5개 랜덤 제공
1. 관련 vod 제공 20개중 5개 랜덤 제공
#236
> [Refactor] : "관련 vod 추천 20개중 5개 제공"

- src/api/ApiService.js
- src/components/CategoryBtn.js
- src/components/MyWish.js
- src/components/Related.js
- src/page/Detail.js
- src/page/Home.js
- src/page/Kids.js
- src/page/Movie.js
- src/page/Tv.js
- src/page/tmp/Socialgoogle.js
- src/page/tmp/Socialkakao.js
- src/page/tmp/Socialnaver.js
카테고리버튼, 디테일 관련vod 구현
1. 영화/ tv/ 키즈 진입시 카테고리 버튼 구현
2. 디테일 페이지 내 관련vod 구현
영화/ tv/ 키즈 진입시 카테고리 버튼으로 진입시 소카테고리가 안뜸.... 수정필요
> [Feat] : "카테고리버튼, 디테일 관련vod 구현"

- contents/views.py
- recommends/urls.py
- recommends/views.py
- requirements.txt
- 신규 유저에 대한 2번 추천 API 작성
구현 사항 요약
1. 신규 유저에 대한 2번 추천 API 작성 
#231
> [Feat]    : "신규 유저에 대한 2번 추천 API 작성"

- contents/views.py
- recommends/urls.py
- recommends/views.py
- requirements.txt
[Deploy]    : "신규 유저에 대한 2번 추천 API 작성"
> [Deploy]    : "신규 유저에 대한 2번 추천 API 작성"

- src/components/CategoryBtn.js
- src/components/MyWish.js
- src/components/Rank.js
- src/components/Related.js
- src/page/Home.js
- src/page/Kids.js
- src/page/Movie.js
- src/page/Tv.js
카테고리 페이지 버그 수정
1. 카테고리 페이지 버그 수정
2. 디테일 페이지 UI 수정
> [Fix - Front]: 카테고리 페이지 버그 수정

- src/App.js
- src/components/CategoryBtn.js
- src/components/Review.js
- src/components/ScrollonTop.js
- src/index.js
- src/layout/Header.js
- src/page/Detail.js
스크롤 버그 수정
1. 페이지 이동 시 스크롤 탑 고정
2. 디테일 페이지 ui 수정
> [Fix - Front] : 스크롤 버그 수정

- src/components/CategoryBtn.js
- src/components/Rank.js
- src/components/Related.js
브라우저 창 크기에 따른 이미지 비율 조정
1. 카테고리 버튼 비율 조정 -> 빔이나 모니터 연결해서 확인 필요...
2. 디테일페이지 내 관련vod 비율 조정
3. 랭크 글자색바꿈
> [Front - Fix] : "브라우저 창 크기에따른 이미지 비율 조정"

- contents/views.py
- recommends/views.py
review 가져올 때 user object MySQL에서 가져오도록 수정
구현 사항 요약
1. review 가져올 때 user object MySQL에서 가져오도록 수정"
2. 신규유저 추천 KNN  n=10으로 수정
#279
> [Back-Fix]     : "review 가져올 때 user object MySQL에서 가져오도록 수정"

- contents/management/commands/dbinsert.py
- contents/views.py
- recommends/views.py
> [Deploy - Hotfix] : "review 가져오기 수정"

- config/settings.py
- recommends/urls.py
- recommends/views.py
크리스마스 시즌 추천 API 제공
구현 사항 요약
1. 크리스마스와 알맞은 컨텐츠 선정
2. 해당 vod 제공
http://127.0.0.1:8000/recommend/6/
> [Feat]    : "시즌별 추천 API"

- .github/workflows/githubaction.yaml
> [Docs]    : "wheel 설치 후 requirements.txt 설치"

- contents/views.py
- sync.py
Kids 컨텐츠 부족으로 인한 에러 처리"
1. kids는 관련 컨텐츠를 kids에서 상위 20개중 5개를 보여줌
#291 
contents/55/detail 에러 처리
> [Back-Fix]     : "Kids 컨텐츠 부족으로 인한 에러 처리"

- src/components/ShowRec.js
- src/page/Home.js
- src/page/tmp/Socialgoogle.js
- src/page/tmp/Socialkakao.js
- src/page/tmp/Socialnaver.js
관심가진 컨텐츠 추천 관련 제목 수정
1. watched 를 제목에 보이기
2. recommend 를 data로 추천 보여주기
생략
#275
> [Front - Feat] : "관심가진 컨텐츠 관련 제목 수정"

- recommends/management/commands/scoreinsert.py
- recommends/urls.py
- recommends/views.py
- 기존 유저에 대한 가장 비슷한 사용자 추천
- url 순서 변경
구현 사항 요약
1. 기존 유저에 대한 가장 비슷한 사용자 추천
2. url 순서 변경
#304 #275 
```
urlpatterns = [
path("1/",MainRecommend1.as_view()),
path("2/", MainRecommend2.as_view()),
path("3/", MainRecommend3.as_view()),
path("4/",FirstUser_Preference_1.as_view()),
path("5/",FirstUser_Preference_2.as_view()),
path("6/",TOP10Recommend.as_view()),
path("7/",timerecommend.as_view()),
path("8/",SeasonRecommend.as_view()),
path("9/",wishlist_recommend.as_view()),
]
```
> [Back-Feat]    : "기존 유저에 대한 가장 비슷한 사용자중 추천"

- src/page/Home.js
- src/page/ShortFilm.js
추천 URL 변경
1. 추천 URL 변경
2. 숏필름 제목 변경
> [Front] 추천 URL 변경

- recommends/views.py
인기 TOP10 로직 변경
구현 사항 요약
1. 인기 TOP10 제공으로 변경
#307
> [Fix]     : "인기 TOP 10 수정"

- directory-visualizer-data.txt
- recommends/admin.py
- recommends/views.py
recommend admin 생성
구현 사항 요약
1. recommend admin 생성
> [Refactor] : "print문 제거, admin에서 장르기반도 보여주기."

- src/layout/Header.js
- src/page/Detail.js
- src/page/Search.js
디테일페이지 내에서 인물검색 연결
1. 배우사진 클릭시 redux 내 searchValue로 저장
2. 검색페이지전환 후 헤더에서 input이 없으면 다시 searchValue가 ""이됨
3. 헤더에서 searchValue가 유지되도록 함 
4. searchValue가 유지되니 페이지 전환해도 검색창이 그대로라서 페이지 이동하면 초기검색창으로 보이게함
> [Feat] : "디테일페이지 내에서 인물검색 연결"

- src/components/CategoryBtn.js
- src/components/MiniSlide.js
- src/components/Review.js
- src/components/ShowData.js
- src/components/ShowRec.js
- src/components/Snow.js
- src/index.css
- src/layout/Header.js
- src/page/First.js
- src/page/Home.js
- src/page/Kids.js
- src/page/Movie.js
- src/page/ShortFilm.js
- src/page/Tv.js
snow 애니메이션 추가
1. snow 컴포넌트 추가
2. 리액트 플레이어 소리버튼 버그 수정
> [Front]: snow 애니메이션 추가

- contents/views.py
배우 검색 수정
배우 검색 시 띄어쓰기를 제거하지 않은 검색 결과도 제시
> [Feat]    : "배우 검색시 띄어쓰기 제거 하지 않고 검색도 추가"

- src/components/MiniSlide.js
- src/components/Modal.js
- src/components/RecMiniSlide.js
- src/components/ShowData.js
- src/components/Snow.js
- src/components/Streaming.js
- src/components/Top5.js
- src/index.js
- src/layout/Header.js
- src/page/About.js
- src/page/Home.js
- src/page/Search.js
- src/page/ShortFilm.css
- src/page/ShortFilm.js
숏필름 클릭 재생 조절
1. 숏필름 클릭 재생 조절
2. 해더 반응형 UI 추가
> [Feat - front]: 숏필름 클릭 재생 조절

- src/App.js
- src/components/MyWish.js
- src/layout/Header.js
- src/page/Login.js
- src/page/ShortFilm.js
- src/page/ShortFilm2.js
react player ui 변경
1. 숏필름 ui 변경
> [Feat - front]: react player ui 변경

- src/components/ShowData.js
- src/page/ShortFilm2.js
숏필름 vodname에 링크 추가
1. 숏필름 vodname에 링크 추가
\
> [Feat]: 숏필름 vodname에 링크 추가
